apiVersion: v1
kind: Service
metadata:
  name: {{ template "yyuap.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
{{- if .Values.nodePort.port }}
      nodePort: {{ .Values.nodePort.port }}
{{- end }}
  selector:
    app: {{ template "yyuap.name" . }}
    release: "{{ .Release.Name }}"

